spring:
  application:
    name: alma-matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/almamatcher
    username: almamatcher
    password: devpassword

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

# alma-matcher props
alma-matcher:
  email-domains:
    - studio.unibo.it
    - unibo.it
  username:
    min-length: 3
    max-length: 20
    pattern: "^[a-z0-9_.]+$"